export const DESCRIPTIONS: Record<string, string> = {
  // Titles
  TITLE_CONTROL_PARAMS: "Parámetros globales que ajustan la sensibilidad y las constantes de la simulación. Modificarlos cambia drásticamente el comportamiento del juego.",
  TITLE_POLICIES: "Definiciones base para cada política, incluyendo sus costos y dinámicas de eficiencia a lo largo del tiempo. Los valores en vivo reflejan el estado actual de la partida.",
  TITLE_LAND_USE: "Propiedades base para cada tipo de uso de suelo, incluyendo sus tasas de emisión y secuestro de carbono. El área en vivo muestra la distribución actual del territorio.",
  TITLE_EQUATIONS: "Las fórmulas matemáticas fundamentales que impulsan la simulación. Muestran cómo se interrelacionan las variables para producir los resultados anuales.",

  // Control Params Table Headers
  PARAM_TABLE_HEADER_KEY: "El nombre único del parámetro en el código fuente de la simulación.",
  PARAM_TABLE_HEADER_VALUE: "El valor numérico o de texto asignado al parámetro para la simulación actual.",

  // Policy Table Headers
  POLICY_TABLE_HEADER_NAME: "El nombre de la política tal como se muestra en la interfaz.",
  POLICY_TABLE_HEADER_COST: "Factor de costo base de la política, expresado como un porcentaje del PBI cuando está activa.",
  POLICY_TABLE_HEADER_DECAY: "Número de años teóricos que tarda la eficiencia de una política en decaer significativamente si no se gestiona. Un número más bajo significa un decaimiento más rápido.",
  POLICY_TABLE_HEADER_EFFICIENCY_LIVE: "La eficiencia actual de la política en el juego (0-100%). Este valor se ve afectado por el tiempo de activación y otros factores como la estabilidad política. Es el multiplicador real del efecto de la política.",
  POLICY_TABLE_HEADER_EFFORT_LIVE: "El esfuerzo total (0-100%) asignado a los instrumentos de esta política (Nivel 2+). Este valor modula la 'Eficiencia Viva' para determinar el impacto final.",

  // Land Use Table Headers
  LAND_USE_TABLE_HEADER_NAME: "El nombre del tipo de uso del suelo.",
  LAND_USE_TABLE_HEADER_EMISSION: "Tasa anual de emisión de carbono (en Mg C por kHa) para este tipo de uso del suelo.",
  LAND_USE_TABLE_HEADER_SEQUESTRATION: "Tasa anual de secuestro de carbono (en Mg C por kHa) para este tipo de uso del suelo.",
  LAND_USE_TABLE_HEADER_AREA_LIVE: "La superficie actual (en miles de hectáreas - kHa) que ocupa este tipo de uso del suelo en la nación.",

  // Equation Section Titles
  EQUATION_TITLE_POLICY_EFFICIENCY: "La fórmula que determina cuán efectiva es una política en un año determinado. Disminuye con el tiempo y se ve afectada por el entorno político.",
  EQUATION_TITLE_CARBON_BALANCE: "La ecuación central para el cambio climático. Calcula la diferencia neta entre el carbono capturado por los ecosistemas y el carbono emitido por las actividades humanas anualmente.",
  EQUATION_TITLE_INDICATORS: "Fórmula genérica que muestra cómo se calculan los indicadores socio-ambientales como la Biodiversidad. Son una suma ponderada de los efectos de las políticas y los usos del suelo.",
  EQUATION_TITLE_POLITICAL_PRESSURE: "Modela cómo aumenta o disminuye el descontento de los grupos de interés. Utiliza una curva 'S' para un comportamiento más realista, donde el cambio es más rápido en niveles intermedios de presión.",
  EQUATION_TITLE_ECONOMY: "Fórmulas que gobiernan la macroeconomía de la nación, incluyendo el crecimiento del PBI y el balance de las finanzas públicas.",
  EQUATION_TITLE_STABILITY_CONFLICT: "Ecuaciones que determinan la cohesión social y la estabilidad del gobierno. Son cruciales para evitar condiciones de fin de juego.",
  EQUATION_TITLE_SCORE: "La fórmula que calcula el Puntaje General. Los componentes y sus pesos cambian en cada nivel para reflejar los desafíos de esa etapa.",

  // CONTROL_PARAMS descriptions
  Max_Emisiones_Referencia_Anual: "Valor máximo de referencia para las emisiones anuales, utilizado en cálculos de normalización internos. No limita las emisiones reales.",
  Ano_Activacion_Prestamo: "El primer año del juego en que la opción de solicitar préstamos se vuelve disponible para el jugador (generalmente en Nivel 3).",
  Max_Abs_Total_Carbon_Ref: "Valor de referencia para el balance de carbono, usado para calcular el componente de carbono en el Puntaje General. Un balance igual a este valor (positivo o negativo) daría 100% o 0% en ese componente.",
  Umbral_polarizacion: "El nivel de diferencia entre la presión política más alta y la más baja que, al ser superado, comienza a contribuir negativamente a la Estabilidad Política.",
  Tasa_Impositiva_General_Sobre_PBI: "La tasa impositiva base que se aplica sobre el PBI para calcular los ingresos del gobierno.",
  Tasa_Base_Crecimiento_PBI: "La tasa de crecimiento anual 'natural' del PBI, antes de ser modificada por los efectos de las políticas.",
  Pago_deuda_anual_Nivel_1: "Porcentaje del capital de la deuda total que se paga anualmente en el Nivel 1.",
  Pago_deuda_anual_Nivel_2: "Porcentaje del capital de la deuda total que se paga anualmente en el Nivel 2.",
  Pago_deuda_anual_Nivel_3: "Porcentaje del capital de la deuda total que se paga anualmente en el Nivel 3.",
  Duracion_Efecto_Al: "Duración del efecto para la política de Conservación de Bienes Naturales (CR, no Al).",
  Duracion_Efecto_CBN: "Duración del efecto para la política de Conservación de Bienes Naturales (CR, no CBN).",
  Duracion_Efecto_CN: "Duración del efecto para la política de Carbono Neutralidad.",
  Duracion_Efecto_EA: "Duración del efecto para la política de Exportaciones Agrícolas.",
  Duracion_Efecto_GRH: "Duración del efecto para la política de Gestión del Recurso Hídrico.",
  Duracion_Efecto_GS: "Duración del efecto para la política de Ganadería Sostenible.",
  Duracion_Efecto_IE: "Duración del efecto para la política de Inversión Extranjera.",
  Duracion_Efecto_NAF: "Duración del efecto para la política de Normativas Ambientales Flexibles.",
  Duracion_Efecto_PA: "Duración del efecto para la política de Políticas Agroecológicas (AS, no PA).",
  Duracion_Efecto_SE: "Duración del efecto para la política de Subsidios Energéticos.",
  Tasa_disipacion_social: "Tasa a la que el 'Conflicto Social' disminuye naturalmente cada año si no hay nuevos factores que lo aumenten.",
  Tasa_de_interes_Nivel_1: "Tasa de interés anual que se aplica sobre la deuda total en el Nivel 1.",
  Tasa_de_interes_Nivel_2: "Tasa de interés anual que se aplica sobre la deuda total en el Nivel 2.",
  Tasa_de_interes_Nivel_3: "Tasa de interés anual que se aplica sobre la deuda total en el Nivel 3.",
  Factor_Impacto_Politicas_y_Presiones_en_Biodiversidad_Peso: "Peso relativo del componente 'Políticas' en el cálculo del cambio anual de la Biodiversidad.",
  Factor_Impacto_Usos_del_Suelo_en_Biodiversidad_Peso: "Peso relativo del componente 'Uso del Suelo' en el cálculo del cambio anual de la Biodiversidad.",
  Factor_Impacto_Politicas_y_Presiones_en_Seguridad_Alimentaria_Peso: "Peso relativo del componente 'Políticas' en el cálculo del cambio anual de la Seguridad Alimentaria.",
  Factor_Impacto_Usos_del_Suelo_en_Seguridad_Alimentaria_Peso: "Peso relativo del componente 'Uso del Suelo' en el cálculo del cambio anual de la Seguridad Alimentaria.",
  Impacto_Biodiversidad_en_Seguridad_Alimentaria_Peso: "Peso relativo del impacto directo de la Biodiversidad sobre la Seguridad Alimentaria.",
  Factor_Impacto_Politicas_y_Presiones_en_Seguridad_Economica_Peso: "Peso relativo del componente 'Políticas' en el cálculo del cambio anual de la Seguridad Económica.",
  Factor_Impacto_Usos_del_Suelo_en_Seguridad_Economica_Peso: "Peso relativo del componente 'Uso del Suelo' en el cálculo del cambio anual de la Seguridad Económica.",
  Impacto_Biodiversidad_en_SE_Peso: "Peso relativo del impacto directo de la Biodiversidad sobre la Seguridad Económica.",
  Peso_Ant_C_SE_Carbono_Stella: "Factor multiplicador del impacto negativo sobre las emisiones de carbono cuando las políticas de 'Neutralidad de Carbono' y 'Subsidios Energéticos' están activas simultáneamente.",
  Peso_Sin_CR_C_Carbono_Stella: "Factor multiplicador del impacto positivo sobre el secuestro de carbono cuando las políticas de 'Conservación' y 'Neutralidad de Carbono' están activas simultáneamente.",
  Tasa_de_BNNP_a_BNP_Base: "Tasa de conversión anual base de Bosque Nativo No Protegido a Bosque Nativo Protegido.",
  Tasa_de_BNNP_a_CA_Base: "Tasa de conversión anual base de Bosque Nativo No Protegido a Cultivos Agroecológicos.",
  Tasa_de_BNNP_a_CC_Base: "Tasa de conversión anual base de Bosque Nativo No Protegido a Cultivos Convencionales.",
  Tasa_de_CA_a_BNNP_Base: "Tasa de conversión anual base (reforestación) de Cultivos Agroecológicos a Bosque Nativo No Protegido.",
  Tasa_de_CC_a_CA_Base: "Tasa de conversión anual base de Cultivos Convencionales a Cultivos Agroecológicos.",
  Factor_Presion_Agricola_PAS: "Impacto de la política Agroecológica sobre la presión del sector agrícola (positivo = aumenta la presión).",
  Factor_Presion_Agricola_PGS: "Impacto de la política de Ganadería Sostenible sobre la presión del sector agrícola (positivo = aumenta la presión).",
  Factor_Presion_Agricola_PPAI: "Impacto de la política de Agricultura Intensiva sobre la presión del sector agrícola (negativo = disminuye la presión).",
  Factor_Presion_Agricola_PPEA: "Impacto de la política de Exportaciones Agrícolas sobre la presión del sector agrícola (negativo = disminuye la presión).",
  Factor_Presion_Ambiental_PAS: "Impacto de la política Agroecológica sobre la presión del sector ambientalista (negativo = disminuye la presión).",
  Factor_Presion_Ambiental_PCR: "Impacto de la política de Conservación sobre la presión del sector ambientalista (negativo = disminuye la presión).",
  Factor_Presion_Ambiental_PGS: "Impacto de la política de Ganadería Sostenible sobre la presión del sector ambientalista (negativo = disminuye la presión).",
  Factor_Presion_Ambiental_PAGUA: "Impacto de la política de Gestión del Agua sobre la presión del sector ambientalista (negativo = disminuye la presión).",
  Factor_Presion_Ambiental_PCN: "Impacto de la política de Neutralidad de Carbono sobre la presión del sector ambientalista (negativo = disminuye la presión).",
  Factor_Presion_Ambiental_PPAI_Neg: "Impacto de la política de Agricultura Intensiva sobre la presión del sector ambientalista (positivo = aumenta la presión).",
  Factor_Presion_Ambiental_PFRA_Neg: "Impacto de la política de Normativas Flexibles sobre la presión del sector ambientalista (positivo = aumenta la presión).",
  Factor_Presion_Ambiental_PSE_Neg: "Impacto de la política de Subsidios Energéticos sobre la presión del sector ambientalista (positivo = aumenta la presión).",
  Factor_Presion_Social_PAS: "Impacto de la política Agroecológica sobre la presión social (negativo = disminuye la presión).",
  Factor_Presion_Social_PAGUA: "Impacto de la política de Gestión del Agua sobre la presión social (negativo = disminuye la presión).",
  Factor_Presion_Social_PCN: "Impacto de la política de Neutralidad de Carbono sobre la presión social (negativo = disminuye la presión).",
  Factor_Presion_Social_PCR: "Impacto de la política de Conservación sobre la presión social (negativo = disminuye la presión).",
  Factor_Presion_Social_PPAI_Neg: "Impacto de la política de Agricultura Intensiva sobre la presión social (positivo = aumenta la presión).",
  Factor_Presion_Social_PPIE_Neg: "Impacto de la política de Inversión Extranjera sobre la presión social (positivo = aumenta la presión).",
  Factor_Presion_Social_PFRA_Neg: "Impacto de la política de Normativas Flexibles sobre la presión social (positivo = aumenta la presión).",
  Sensibilidad_PP_Agricola_SegEconomica: "Factor que multiplica la diferencia entre el umbral y el valor real de la Seguridad Económica para generar presión agrícola.",
  Umbral_PP_Agricola_SegEconomica: "Valor de Seguridad Económica por debajo del cual el sector agrícola comienza a generar presión.",
  Sensibilidad_PP_Agricola_SegAlimentaria: "Factor que multiplica la diferencia entre el umbral y el valor real de la Seguridad Alimentaria para generar presión agrícola.",
  Umbral_PP_Agricola_SegAlimentaria: "Valor de Seguridad Alimentaria por debajo del cual el sector agrícola comienza a generar presión.",
  Sensibilidad_PP_Ambiental_Biodiversidad: "Factor que multiplica la diferencia entre el umbral y el valor real de la Biodiversidad para generar presión ambientalista.",
  Umbral_PP_Ambiental_Biodiversidad: "Valor de Biodiversidad por debajo del cual el sector ambientalista comienza a generar presión.",
  Sensibilidad_PP_Ambiental_BalanceCarbono: "Factor que multiplica el déficit de carbono (si es negativo) para generar presión ambientalista.",
  EfectoPositivo_PP_Ambiental_BalanceCarbono: "Pequeño efecto de reducción de presión si el balance de carbono es positivo.",
  Sensibilidad_PP_Social_BienestarSocial: "Factor que multiplica la diferencia entre el umbral y el valor real del Bienestar Social para generar presión social.",
  Umbral_PP_Social_BienestarSocial: "Valor de Bienestar Social por debajo del cual se comienza a generar presión social.",
  PRESION_PUNTO_EQUILIBRIO: "El valor de presión (0-100) hacia el cual todos los grupos de presión tienden a normalizarse si no hay otros impulsos.",
  PRESION_TASA_NORMALIZACION: "La velocidad (porcentaje por año) a la que la presión se mueve hacia el Punto de Equilibrio.",
  Factor_Reduccion_Emisiones_Renovables_PCN: "Factor de reducción de emisiones que se aplica al activar el instrumento de 'Fomento a Energías Renovables' en la política de Neutralidad de Carbono.",
  Factor_Aumento_Secuestro_CAC_PCN: "Cantidad de secuestro de carbono adicional que se obtiene al activar el instrumento de 'I+D en Captura de Carbono' en la política de Neutralidad de Carbono.",
  Factor_Aumento_Emisiones_Fosiles_PSE: "Factor de aumento de emisiones que se aplica al activar instrumentos de la política de 'Subsidios Energéticos'.",
  Max_Additional_Tax_Rate_Percentage: "La tasa impositiva adicional máxima que el jugador puede aplicar en el Nivel 3.",
  EcoSec_Reduction_Factor_Per_Tax_Point: "Puntos de reducción en la Seguridad Económica por cada punto porcentual de impuesto adicional aplicado.",
  SocialConflict_Increase_Factor_Per_Tax_Point: "Puntos de aumento en el Conflicto Social por cada punto porcentual de impuesto adicional aplicado.",
  PBIGrowth_Reduction_Factor_Per_Tax_Point: "Reducción en la tasa de crecimiento del PBI por cada punto porcentual de impuesto adicional aplicado.",
  PPSocial_Increase_Factor_Per_Tax_Point: "Puntos de aumento en la Presión Social por cada punto porcentual de impuesto adicional aplicado.",
};